name: TEST CI/CD
on: [push]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Gathering info
        env: # Or as an environment variable
          DOCKER_NAME: ${{secrets.DOCKER_NAME}}
        run: echo "$DOCKER_NAME"
