name: TEST CI/CD
on: [push]
jobs:
  build_image:
    runs-on: ls-home
    env: # Or as an environment variable
      DOCKER_NAME: ${{secrets.DOCKER_NAME}}
      DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}    
    
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker
        run: docker login -u $DOCKER_NAME --password $DOCKER_TOKEN

      - name: check repo
        run: ls -la

      - name: Build Image
        run: docker build . -t test:latest

      - name: Docker tag 
        run: docker image tag test:latest docker.io/$DOCKER_NAME/test:latest

      - name: Docker push image
        run:  docker image push docker.io/$DOCKER_NAME/test:latest

  start_container:
    needs: build_image
    runs-on: bobtrade
    steps:
      - uses: actions/checkout@v2

      - name: check repo
        run: ls -la
        
  try_env:
    needs: start_container
    runs-on: bobtrade
    environment:
      name: DEV
    env: # Or as an environment variable
      ENV: ${{secrets.env}}
    steps:
      - uses: actions/checkout@v2

      - name: check repo
        run: ls -la

      - name: check ENV variable
        run: cd $ENV; ls -la

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: DEV.txt
          path: DEV/DEV.txt

