name: TEST CI/CD
on: [push]
jobs:
  build_image:
    runs-on: ubuntu-latest
    env: # Or as an environment variable
      DOCKER_NAME: ${{secrets.DOCKER_NAME}}
      DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}    
    
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker

        run: echo "$DOCKER_NAME" docker login -u $DOCKER_NAME --password $DOCKER_TOKEN

      - name: check repo
        run: ls -la

      - name: Build Image
        run: docker build . -t test:latest

      - name: Docker tag 
        run: docker image tag test:latest test:latest

      - name: Docker push image
        run:  docker image push docker.io/$DOCKER_NAME/test:latest
